### ISSUE TITLE
0.2.0 tasks/ideas

### ISSUE THREAD

**Issue by mbuscemi** [mbuscemi/elm-test-runner#2]
- [x] Config Option: Auto-run.
- [x] Config Option: Auto-navigate.
- [x] Config Option: Set alternate path for elm-test.
- [x] Display whether or not the entire project passes `elm-format --validate`.
- [x] If the project does not pass format validation, highlight offending files (with linter?)
- [x] Run `elm-verify-examples` on test files before running tests.
- [x] Enable/disable running of `elm-verify-examples`.
- [x] Kill test process on plugin deactivation if it's still around for some reason.
- [x] Investigate correcting UI under Nord Atom theme.
- [x] Ability to copy text out of the output display.
- [x] When searching for the directory to run `elm-test` against, only consider a directory valid if it has an elm-package.json file _and_ has a `tests` subdirectory.
- [x] When searching for the directory to run in, as a last resort, check immediate subdirectories of all project directories.
- [x] When searching for a working test directory, also search subdirectories recursively, though it will be necessary to do some filtering: directories that begin with ".", "elm-stuff", "node_modules", etc.

**Comment by mbuscemi** [comment]
After some investigation into the first two, I'm deciding to nix them as features. I remember now that I'd gotten these values nicely decoupled from the Atom JS layer and implementing the key hooks would necessitate moving that logic out of Elm. I'm going to leave them as is for now, though if I ever need to free up the UI space they occupy, this is exactly where they're going.

**Comment by mbuscemi** [comment]
After investigating `elm-format --validate`, I've come to a couple of conclusions. First, adding output of this nature to the UI would be confusing. The test tree is clearly derived from test files. How and where would the elm-format validation data be displayed? This led me to my second conclusion, I think that elm-format validation, while a good idea generally, sits outside the scope of this project, whose goal is to provide an in-Atom visualization for elm-test.

Does this mean a new project? Perhaps suggesting features from an existing project? @zwilias, What do you think?

**Comment by zwilias** [comment]
Agreed. The `--validate` feature is meant for continuous integration systems anyway. Not broadening the scope for a very questionable feature = 👍

**Comment by mbuscemi** [comment]
Cool. Thanks!

**Comment by mbuscemi** [comment]
#3 Added some changes to address this:
* When searching for the directory to run `elm-test` against, only consider a directory valid if it has an elm-package.json file and has a `tests` subdirectory.
* When searching for the directory to run in, as a last resort, check immediate subdirectories of all project directories.

**Comment by mbuscemi** [comment]
0.2.0 has been released.
