### ISSUE TITLE
Figure out a strategy for running --add-dependencies

### ISSUE THREAD

**Issue by mbuscemi** [mbuscemi/elm-test-runner#9]
It seems like the test runner should be capable of doing this if dependencies are out of date. Perhaps some kind of detection of that particular compilation failure case? I'll have to do some investigate at a later date. Perhaps this can be a focus for 0.4.0.

**Comment by mbuscemi** [comment]
I'm having trouble reproing this. It looks as though elm-test will automatically add dependencies if they're not there. If I can get repro steps, I'll re-open this in the future.

**Comment by zwilias** [comment]
It shouldn't; though if the missing dependency isn't relevant to any of the code referenced in tests, it would "just work".
